language: rust
rust:
  - stable
  - beta
  - nightly
script:
  - cargo test
  - cargo test --release
  - cargo test --all-features
  - cargo test --all-features --release
  - cargo test --features "https"
  - cargo test --features "json-using-serde"
  - cargo test --features "punycode"
  - cargo test --features "proxy"
